### ISSUE TITLE
[QUESTION, FEATURE] Add ability to look up players on the high scores

### ISSUE THREAD

**Issue by jfpiv** [Wingman/wingman#1]
I would like to write a "HiscorePlayer" class that represents a player on the hiscores. However, I am not sure where to place this class in the directory structure.

**Comment by alexanderhenne** [comment]
If I were to implement this, I would include it in the default Developer Utilities plugin that will soon be available on https://github.com/Wingman/wingman-defaultplugins.

**Comment by oplosthee** [comment]
[This issue has been resolved.](https://github.com/Wingman/wingman-defaultplugins/pull/1)
Thanks again for your contribution.
