### ISSUE TITLE
Plugins not working/loading

### ISSUE THREAD

**Issue by Woolba** [Wingman/wingman#15]
Plugins are not loading. Tested with provided .jar files and compiled from source. Placing latest plugins in plugin folder produces the following messages in terminal:

`23:47:49.857 [main] INFO uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4J - Replaced standard System.out and System.err PrintStreams with SLF4JPrintStreams
23:47:49.862 [main] INFO uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4J - Redirected System.out and System.err to SLF4J for this context
23:47:50.325 [SwingWorker-pool-1-thread-1] INFO com.wingman.client.rs.GameDownloader - Attempting to load world 313
23:47:51.420 [SwingWorker-pool-1-thread-2] INFO com.wingman.client.plugin.PluginManager - Finding and setting up plugins
23:47:52.045 [SwingWorker-pool-1-thread-2] INFO org.reflections.Reflections - Reflections took 582 ms to scan 25 urls, producing 1185 keys and 6987 values 
23:47:52.069 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - com.wingman.client.plugin.exceptions.PluginLoadingException: GroundItems loading error: The expected dependency plugin DevUtils of minimum version 1.0.2 is not installed.
23:47:52.069 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at com.wingman.client.plugin.PluginManager.parsePluginDependencies(PluginManager.java:150)
23:47:52.069 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at com.wingman.client.plugin.PluginManager.findAndSetupPlugins(PluginManager.java:48)
23:47:52.069 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at com.wingman.client.rs.GameLoader.doInBackground(GameLoader.java:31)
23:47:52.070 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at com.wingman.client.rs.GameLoader.doInBackground(GameLoader.java:20)
23:47:52.070 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
23:47:52.070 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
23:47:52.070 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at javax.swing.SwingWorker.run(SwingWorker.java:334)
23:47:52.070 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
23:47:52.070 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
23:47:52.070 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at java.lang.Thread.run(Thread.java:745)
23:47:52.409 [SwingWorker-pool-1-thread-2] INFO com.wingman.client.rs.GameLoader - Loading the game
23:47:52.702 [SwingWorker-pool-1-thread-2] INFO com.wingman.client.rs.GameAppletStub - Loading applet parameters`

Compiling the latest devutils from source (also tested with the provided .jar) provides the following messages in terminal:

`23:50:32.956 [main] INFO uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4J - Replaced standard System.out and System.err PrintStreams with SLF4JPrintStreams
23:50:32.961 [main] INFO uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4J - Redirected System.out and System.err to SLF4J for this context
23:50:33.410 [SwingWorker-pool-1-thread-1] INFO com.wingman.client.rs.GameDownloader - Attempting to load world 313
23:50:34.482 [SwingWorker-pool-1-thread-2] INFO com.wingman.client.plugin.PluginManager - Finding and setting up plugins
23:50:35.090 [SwingWorker-pool-1-thread-2] INFO org.reflections.Reflections - Reflections took 569 ms to scan 26 urls, producing 1185 keys and 6992 values 
23:50:35.112 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - com.wingman.client.plugin.exceptions.PluginLoadingException: GroundItems loading error: The expected dependency plugin DevUtils of minimum version 1.0.2 is not installed.
23:50:35.113 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at com.wingman.client.plugin.PluginManager.parsePluginDependencies(PluginManager.java:150)
23:50:35.113 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at com.wingman.client.plugin.PluginManager.findAndSetupPlugins(PluginManager.java:48)
23:50:35.113 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at com.wingman.client.rs.GameLoader.doInBackground(GameLoader.java:31)
23:50:35.113 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at com.wingman.client.rs.GameLoader.doInBackground(GameLoader.java:20)
23:50:35.114 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
23:50:35.114 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
23:50:35.114 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at javax.swing.SwingWorker.run(SwingWorker.java:334)
23:50:35.114 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
23:50:35.114 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
23:50:35.114 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at java.lang.Thread.run(Thread.java:745)
23:50:35.467 [SwingWorker-pool-1-thread-2] INFO com.wingman.client.rs.GameLoader - Loading the game
23:50:35.735 [SwingWorker-pool-1-thread-2] INFO com.wingman.client.rs.GameAppletStub - Loading applet parameters
23:50:35.806 [SwingWorker-pool-1-thread-2] INFO com.wingman.client.plugin.PluginManager - Activated plugin Developer Utilities (DevUtils-bA5UvUk4V 1.1.1)
23:50:42.083 [AWT-EventQueue-0] INFO com.wingman.client.plugin.PluginManager - Deactivated plugin Developer Utilities (DevUtils-bA5UvUk4V 1.1.1)`

And finally, compiling devutils 1.0.2 (and testing with the provided .jar) provides the following messages in terminal:

`23:53:54.758 [main] INFO uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4J - Replaced standard System.out and System.err PrintStreams with SLF4JPrintStreams
23:53:54.763 [main] INFO uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4J - Redirected System.out and System.err to SLF4J for this context
23:53:55.203 [SwingWorker-pool-1-thread-1] INFO com.wingman.client.rs.GameDownloader - Attempting to load world 313
23:53:56.300 [SwingWorker-pool-1-thread-2] INFO com.wingman.client.plugin.PluginManager - Finding and setting up plugins
23:53:56.942 [SwingWorker-pool-1-thread-2] INFO org.reflections.Reflections - Reflections took 599 ms to scan 26 urls, producing 1185 keys and 6992 values 
23:53:57.312 [SwingWorker-pool-1-thread-2] INFO com.wingman.client.rs.GameLoader - Loading the game
23:53:57.639 [SwingWorker-pool-1-thread-2] INFO com.wingman.client.rs.GameAppletStub - Loading applet parameters
23:53:57.716 [SwingWorker-pool-1-thread-2] INFO com.wingman.client.plugin.PluginManager - Activated plugin Developer Utilities (DevUtils 1.0.2)
23:53:57.719 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - com.wingman.client.plugin.exceptions.PluginLoadingException: GroundItems loading error: java.lang.reflect.InvocationTargetException
23:53:57.719 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at com.wingman.client.plugin.PluginManager.activatePlugins(PluginManager.java:360)
23:53:57.719 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at com.wingman.client.rs.GameLoader.doInBackground(GameLoader.java:72)
23:53:57.720 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at com.wingman.client.rs.GameLoader.doInBackground(GameLoader.java:20)
23:53:57.720 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
23:53:57.720 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
23:53:57.720 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at javax.swing.SwingWorker.run(SwingWorker.java:334)
23:53:57.720 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
23:53:57.720 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
23:53:57.720 [SwingWorker-pool-1-thread-2] ERROR java.lang.Throwable - 	at java.lang.Thread.run(Thread.java:745)`

These were tested on the latest stable and git code, and on both Linux with OpenJDK 1.8.0_112 and Windows with Oracle's Java 1.8.0_121. Same errors.

**Comment by oplosthee** [comment]
The GroundItems plugin in the default plugins repository is outdated and does not work with the current API (GroundItems was last updated 8 months ago). I was working on making a new version a while ago using callbacks and such, but ran into some difficulties with item despawning and haven't worked on it since.

If you know a bit of Java and want to create your own GroundItems plugin without the callbacks, you can use [this snippet](https://gist.github.com/oplosthee/fe7303f395de0058dd121d6e72e1360a) as an example on how to get items on the ground using the current API. You can ask questions about plugin development in the Slack, if you might have any.
