### ISSUE TITLE
Loading plugins

### ISSUE THREAD

**Issue by Shyann** [Wingman/wingman#2]
I downloaded the default plugins and put them in the plugins folder but they don't seem to load.

**Comment by oplosthee** [comment]
Hello,

I cannot reproduce the issue you're having on my own system. For reference, these are the steps I followed:
1. Downloaded `Wingman.jar` from the [Wingman releases](https://github.com/Wingman/wingman/releases/tag/1.116.0) for the current RuneScape revision.
2. Started the client and let it download the current RuneScape gamepack, closing it after the download finished.
3. Downloaded `Wingman-defaultplugins.jar` from the [Wingman default plugin releases](https://github.com/Wingman/wingman-defaultplugins/releases).
4. Saved the `Wingman-defaultplugins.jar` to `%user.home%/Wingman/plugins` (For Windows systems, `C:\Users\<LOGIN_NAME>\Wingman\plugins`)
5. Started the client, after which the plugins loaded without any difficulties.

Could you please tell me what steps you followed, so I can reproduce this bug (if possible)?

**Comment by Shyann** [comment]
Thanks! That's fixed the issue for me. The error was caused from putting the source files in the plugins folder rather than the jar files. Are there any guides on how to create plugins?

**Comment by oplosthee** [comment]
That's good to hear! At the moment we do not have any guides on how to write plugins yet, but this is something we will definitely do in the near future. 

For now the best way to create a plugin would be to look at an existing plugin (currently only [GroundItems](https://github.com/Wingman/wingman-defaultplugins/blob/master/src/main/java/com/wingman/defaultplugins/grounditems/GroundItems.java)) and the [API overview](https://wingman.github.io/javadoc/) (especially `com.wingman.client.api.generated.Static` might contain what you're looking for). We're also using [Slack](http://wingman-slack.herokuapp.com/), on which you can ask questions if you have any.

**Comment by Shyann** [comment]
Cool, thanks!
