### ISSUE TITLE
Feature Request: External player update events.

### ISSUE THREAD

**Issue by ghost** [Wingman/wingman#5]
I'm not quite sure how I'd add these hooks/events myself as I'm not really familiar with the code-base just yet, but I'd like to write a plugin that would allow players to see how populated certain spots are in the game, allowing them to easily choose other training spots or hop to another world if the server is overpopulated.

This could be done by hooking `dm.b(Ldk;II)Z` method in rev `117`. The 1st parameter is the buffer that player position data is read from, and the 2nd parameter is the index of the external player being updated.

You can find more information about this topic [here](http://rs-hacking.com/forum/index.php?/topic/1156-osrs-tracking-the-movement-of-any-player-in-your-world) and [here](https://www.rune-server.org/runescape-development/rs-503-client-server/informative-threads/257340-player-updating-procedure.html)

**Comment by alexanderhenne** [comment]
The event will be added when our mapper maps most of the classes/methods/fields.

**Comment by alexanderhenne** [comment]
Added required API for this, event is still to be added.

**Comment by Chnkr** [comment]
:+1:

**Comment by alexanderhenne** [comment]
Added in 695dda1b78e89012f5d6e86dedc0cfeae84e5aa5 (ExternalPlayerMovedEvent)

Check out the wiki article over at https://github.com/Wingman/wingman/wiki/Using-event-listeners if you're not familiar with using event listeners yet.

**Comment by ghost** [comment]
:+1: Thanks a ton for this!
