### ISSUE TITLE
Considering using Wingman to create an overlay

### ISSUE THREAD

**Issue by atkinscollin** [Wingman/wingman#8]
Hi, I was looking into creating an overlay using your client as a base. I have been looking for a client where I can create my own overlay/plugins and searching github I find this gem. It looks like you have created a cool public client I can push too. 
The overlay I want to create would take text from objects you look at in game (ex. you scroll over a tree and it says chop tree, examine tree) and overlay it with a different language. I have a couple ideas on how I would do this at the moment: have it auto-translated using google translate to translate to any language available (this would be best, but I doubt it is possible), have it auto-translate using an English to X dictionary (would be great too, but work on one language at a time), have a file that you can input word->translated_word so that when that word appears on screen another word is replace by it (would be weak but put user in control).
I want to create this to help myself learn languages easier (learn while you play, how nice), but also have it be distributed so others can use it too.
Do you think working on this client would be optimal? Or should I take another route?

**Comment by oplosthee** [comment]
Hello,

It's definitely possible to do this, although it is not possible to translate all text/names/strings through the API in its current state. For now you would be able to translate names of NPCs (through [NPCDefinition](https://github.com/Wingman/wingman/blob/master/src/main/java/com/wingman/client/api/generated/NPCDefinition.java)) and text from items (through [ItemDefinition](https://github.com/Wingman/wingman/blob/master/src/main/java/com/wingman/client/api/generated/ItemDefinition.java)), so you could already add translations for items and NPCs and work on the translation process itself. I'll take a look at getting the names for other objects like rocks, trees and such and add it to the API as soon as possible. Feel free to ask any questions you have on Slack as well.

Good luck with your plugin!
